"""update stock columns

Revision ID: c01f268301e1
Revises: d7cc3f51dd03
Create Date: 2026-03-12 11:05:42.574888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'c01f268301e1'
down_revision: Union[str, Sequence[str], None] = 'd7cc3f51dd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE products SET stock = 0 WHERE stock IS NULL"
    )
    op.alter_column('products', 'stock',
               existing_type=mysql.INTEGER(),
               nullable=False,
               server_default="0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
