"""add stock, date_created, date_modified columns

Revision ID: d7cc3f51dd03
Revises: 
Create Date: 2026-03-11 22:33:58.258277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7cc3f51dd03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               nullable=True)
    op.drop_column('products', 'date_modified')
    op.drop_column('products', 'date_created')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
